export const flashCardList = [
    {front: "What does HTML stand for?", 
    back: "HyperText Markup Language — the structure of web pages."},
    {front: "What is the purpose of the <head> tag?", 
    back: "Contains metadata, links, title, scripts, and CSS — not visible content."},
    {front: "What does the <meta charset=\"UTF-8\"> tag do?", 
    back: "Specifies the character encoding for the HTML document, ensuring proper display of text."},
    {front: "What does the <a> tag do?", 
    back: "Defines a hyperlink, which is used to link from one page to another."},
    {front: "Difference between <div> and <span>?", 
    back: "<div> is a block-level element used for grouping larger sections, while <span> is an inline element used for styling small parts of text."},
    {front: "What does the <img> tag require?", 
    back: "Specifies an image to be embedded in the document, requires the src attribute for the image URL and alt attribute for alternative text."},
    {front: "What is semantic HTML?", 
    back: "Uses HTML elements according to their meaning to improve accessibility and SEO."},
    {front: "What is the purpose of the <form> tag?", 
    back: "Defines a section for user input, allowing data submission to a server."},
    {front: "What does the <script> tag do?", 
    back: "Used to embed or reference executable JavaScript code within an HTML document."},
    {front: "What is the DOM?", 
    back: "The Document Object Model (DOM) is a programming interface for HTML and XML documents. It represents the page so that programs can change the document structure, style, and content."},
    {front: "What does CSS stand for?", 
    back: "Cascading Style Sheets — used for describing the presentation of a document written in HTML or XML."},
    {front: "What is the CSS Box Model?", 
    back: "Describes the rectangular boxes generated for elements in the document tree, including margins, borders, padding, and the actual content."},
    {front: "What is the difference between class and id selectors?", 
    back: "Class selectors target multiple elements with the same class attribute, while id selectors target a unique element with a specific id attribute."},
    {front: "What does display: flex do?", 
    back: "Enables a flex container, allowing flexible and responsive layout of its child elements."},
    {front: "What does display: grid do?", 
    back: "Enables a grid container, allowing layout of child elements in rows and columns."},
    {front: "What is position: absolute?", 
    back: "Positions an element relative to its nearest positioned ancestor, removing it from the normal document flow."},
    {front: "What is the difference between margin and padding?", 
    back: "Margin is the space outside an element's border, while padding is the space between the content and the border of an element."},
    {front: "How do you change text color in CSS?", 
    back: "Use the color property, e.g., color: red;"},
    {front: "How do you import a Google Font?", 
    back: "Use the @import rule in your CSS or link to the font in the HTML <head> using a <link> tag."},
    {front: "What does z-index control?", 
    back: "Controls the stacking order of elements, determining which elements appear in front of or behind others."},
    {front: "What is JavaScript used for on websites?", 
    back: "Adds interactivity and dynamic behavior to web pages."},
    {front: "What is a variable?", 
    back: "A storage location identified by a name that holds data which can be changed during program execution."},
    {front: "Difference between let and const?", 
    back: "let allows you to declare variables that can be reassigned, while const declares variables that cannot be reassigned after their initial assignment."},
    {front: "What is an array?", 
    back: "An ordered collection of elements, which can be of any type, accessible by their index."},
    {front: "What is a function?", 
    back: "A block of reusable code that performs a specific task."},
    {front: "What is an event listener?", 
    back: "A procedure in JavaScript that waits for an event to occur, such as a user clicking a button."},
    {front: "What is the difference between == and ===?", 
    back: "== compares values for equality after type coercion, while === compares both value and type without coercion."},
    {front: "What is a JSON object?", 
    back: "A lightweight data-interchange format that is easy for humans to read and write, and easy for machines to parse and generate."},
    {front: "What is DOM manipulation?", 
    back: "The process of using JavaScript to change the structure, style, or content of the Document Object Model (DOM) of a web page."},
    {front: "What is the difference between `null` and `undefined`?", 
    back: "`undefined` means a variable has been declared but not assigned. `null` is an assigned value meaning “no value” or “empty.”"}
]